### ISSUE TITLE
Image urls from field seo_image

### ISSUE THREAD

**Issue by webmanufaktur** [adrianbj/MarkupSEO#1]
**Expected behavior**
Image url or image httpUrl:
http://domain.tld/site/assets/files/1234/seoimage_1-1.jpg
or
/site/assets/files/1234/seoimage_1-1.jpg

**Actual behavior**
Only file name in frontend

![2018-07-25 20_01_22-view-source_pwaffiliate test_weekender_weekender-12446_](https://user-images.githubusercontent.com/5909089/43218786-b6770864-9045-11e8-96e2-831da315f7f8.png)

**Comment by adrianbj** [comment]
I am not seeing this - are you using the latest commit on this branch:
https://github.com/adrianbj/MarkupSEO/tree/various-fixes-enhancements

**Comment by adrianbj** [comment]
This is the relevant block:
https://github.com/adrianbj/MarkupSEO/blob/f97fe93a0917e6c00d8501b51663a0837816b40d/MarkupSEO.module#L275-L297

Perhaps you seeing an image coming from this line: https://github.com/adrianbj/MarkupSEO/blob/f97fe93a0917e6c00d8501b51663a0837816b40d/MarkupSEO.module#L288

Maybe that's the issue?

**Comment by adrianbj** [comment]
Looking into this more now - it is an issue with page specific images - I'll have a fix soon.

**Comment by adrianbj** [comment]
I think this and Issue#2 should now be fixed, but would appreciate if you could check. I'll leave it to you to close both of these if everything is now working as expected.

Thanks!

**Comment by webmanufaktur** [comment]
Fixed. 

Version: 0d7b30069c2498a58e81fb9c809fa5112e12af51
