### ISSUE TITLE
Template defaults for smart image shows all image fields, not only those within template

### ISSUE THREAD

**Issue by webmanufaktur** [adrianbj/MarkupSEO#3]
**Expected behavior**
Showing only image fields already defined in template.
Should exclude the _seo_image_ field as well.

**Actual behavior**
Shows all existing image fields in ProcessWire instance.

![2018-07-25 20_06_37-modules processwire pwaffiliate test](https://user-images.githubusercontent.com/5909089/43218994-63cec7b8-9046-11e8-869c-2dcc04120370.png)

**Comment by adrianbj** [comment]
Fixed by https://github.com/adrianbj/MarkupSEO/commit/4e115faebaef0190e3169e29e4b1e5a62be49e19
