### ISSUE TITLE
Custom meta tags get merged/mixed when more than one is defined

### ISSUE THREAD

**Issue by webmanufaktur** [adrianbj/MarkupSEO#4]
**Expected behavior**
Each custom meta tag on its own. Line by line.

**Actual behavior**
_Two+ custom meta tags get merged/mixed_

![2018-07-25 20_15_16-view-source_pwaffiliate test_weekender_weekender-12446_](https://user-images.githubusercontent.com/5909089/43219442-9c426aa4-9047-11e8-93b3-b5f491cbb507.png)

**Tested with**
lasttest := 20180725
initialtest := 20180721

**Comment by adrianbj** [comment]
I just tested and it works for me:

![image](https://user-images.githubusercontent.com/871211/43223883-5a4cc3d0-9009-11e8-9379-61e771aec3c0.png)

![image](https://user-images.githubusercontent.com/871211/43223890-612be56e-9009-11e8-948e-f1fae5bed3ca.png)

Not sure how to start debugging why it's not working at your end - maybe a system line break issue? Perhaps you wouldn't mind debugging this line: https://github.com/adrianbj/MarkupSEO/blob/7438ee23066ff03e0488318995ea8c73a89a1222/MarkupSEO.module#L430 to see if you can get things working at your end. Maybe it's better just being `"\n"`

**Comment by webmanufaktur** [comment]
Changing that line fixes the problem.

`$lines = explode("\n", $custom);`

That works now.

**Comment by adrianbj** [comment]
Thanks - fixed in https://github.com/adrianbj/MarkupSEO/commit/ffce02f953b567b0b9d4057f9f851b4348dcb3c0
