### ISSUE TITLE
Implement size() for seo_image

### ISSUE THREAD

**Issue by qbixx** [adrianbj/MarkupSEO#5]
Currently the `seo_image` field is displaying the direct URL to the original image that is being set in the Smart Image field. Since users of the CMS can upload their own images for most of these image fields, it would be great if we could use the `->size()` tag to resize these images accordingly.

As an example, on my website the seo_image is accounting for about 20% of the bandwidth that the website is using.

**Comment by adrianbj** [comment]
Hi @qbixx - maybe I am not quite following you. Are you talking about the automatic output to:
```
<meta property="og:image"
```
Or are you manually trying to insert the image somewhere?

**Comment by qbixx** [comment]
Hi @adrianbj - sorry, i'm currently adding the metatags manually to the page. Therefore i've changed the 'method' from 'Automatically' to 'Manually' on the settings page of the module.

In my theme file I'm using the code below:
```
<meta property="og:image" content="<?= $page->seo->image; ?>">
<meta name="twitter:image" content="<?= $page->seo->image; ?>">
```

This outputs the original file path of the image that is being uploaded. The file size for these images can be quite big, as they can be changed by an administrator of the website (i'm using the 'Smart Image' field to match the image with an field on the page).

It would be great if we could create a smaller version of the original image for these image metatags. Facebook uses for their link sharing e.g. 1200 x 628. It would be great if we could use the resizing options that ProcessWire facilitates. E.g.:

```
<meta property="og:image" content="<?= $page->seo->image->size(1200, 628); ?>">
```

**Comment by adrianbj** [comment]
I'll need to take a good look at this when I have a little more time, but in the meantime you should be able to do something like this:
```
$page->get($modules->get('MarkupSEO')->blog_imageSmart)->first()->size(200,200)->url;
```
That assumes you set the smartImage on the blog template. Obviously you can adjust as necessary or remove the `blog_` completely if you set it overall rather than at the template level.

The other option of course is to just call the image field itself directly, rather than via the SEO module's smartImage field link. I feel like the smartImage option really only makes sense if you're using the automatic method.

**Comment by adrianbj** [comment]
@qbixx - I have been looking at this again and I am still confused about what you are doing. In the issue title above you mention `seo_image` but then a few posts down you write `$page->seo->image`

These are obviously very different things and I am not sure that either are relevant to the smartImage field that you also mention. Perhaps it would be helpful if you could please post screenshots showing the relevant section from the module settings, and also the image field on the SEO tab so I can be certain of exactly what you have setup at your end.

**Comment by adrianbj** [comment]
@qbixx - any chance of the further clarification I asked for? It would be good to get this sorted out.

**Comment by qbixx** [comment]
@adrianbj Sure, no problem!

To have more control over the metatags that are being outputted in `<head>` I'm using the manual way instead of the automatic solution.

When using the manual code I normally add the code like below to output the corresponding metatags:

```
<?php if ($page->seo->image) : ?>
<meta property="og:image" content="<?= $page->seo->image; ?>">
<meta name="twitter:image" content="<?= $page->seo->image; ?>">
<?php endif; ?>
```

The big advantage is that I don't have to check which template file is being used and that I can use different image fields (i'm not always using the exact same field_name for these type of images). The image fields can then be selected from the MarkupSEO modules page and the correct images are being printed out without the need to add some logic to the variable that is being used for printing out the image metatags.

It might of course be possible that i'm not using the module the way it's intended, but that's how I normally implement this module into the template.

**Comment by adrianbj** [comment]
Instead of `$page->seo->image` do you mean `$page->seo_image` ?

**Comment by qbixx** [comment]
I'm currently using `$page->seo->image`, `$page->seo_image` only returns an empty string.

The following code:

```
<meta property="og:image" content="<?= $page->seo->image; ?>">
<meta property="og:image" content="<?= $page->seo_image; ?>">
```

Results in:
```
<meta property="og:image" content="http://domain.com/site/assets/files/1054/90306770.jpg">
<meta property="og:image" content="">
```

**Comment by adrianbj** [comment]
This works for me:

![image](https://user-images.githubusercontent.com/871211/49951743-804c0e00-feaf-11e8-899c-6c97354c62c9.png)

Does using first() fix it for you?

Note that the current versions of this module and Tracy don't actually allow this to work in the Console panel - I have had to update both locally but I will push shortly.

**Comment by adrianbj** [comment]
I have pushed those updates to both modules so now you can easily do these tests from the Tracy Console panel either on the frontend, or also when editing a page in the backend.

**Comment by qbixx** [comment]
Thanks, i've just both updated MarkSEO (with the `various-fixes-enhancements` branche) and Tracy.

I'm getting the following error when trying to run the code:
![screenshot 2018-12-14 at 14 46 34](https://user-images.githubusercontent.com/1932778/50006774-20d52780-ffaf-11e8-9d61-43f50da7e850.png)

**Comment by adrianbj** [comment]
@qbixx - I think what is probably going on here is that you originally installed the master version of the module, but in my `various-fixes-enhancements` branch I have changed the fieldtype for the seo image from text to image: https://github.com/adrianbj/MarkupSEO/commit/9549ee2e871ce8c15c109b67917da8249d6f4201

Can you please try installing this branch from scratch on a different installation (where the master has never been installed, or at least uninstalled) and see if it works ok.

I know this is a pain, but I think it was necessary to get a better experience.

**Comment by qbixx** [comment]
@adrianbj - Previously the module indeed was installed through the `master` branche. I've uninstalled the module, removed the MarkupSEO folder from within the /modules folder, downloaded the `various-fixes-enhancements` branche and reinstalled the module.

This option worked when I manually added a new image for a specific page on the SEO tab. However when using the image field that is set through a Smart Image field, i'm getting the following:

I've tried both options:
![screenshot 2018-12-15 at 19 04 44](https://user-images.githubusercontent.com/1932778/50045985-69b6da00-009c-11e9-9d4a-0d75520e1188.png)

![screenshot 2018-12-15 at 19 04 58](https://user-images.githubusercontent.com/1932778/50045986-6cb1ca80-009c-11e9-9880-9f64537aa909.png)

**Comment by adrianbj** [comment]
Ah, yes, good point about the smart image field - sorry about that.

It's a rush job, but please try the latest commit.

**Comment by qbixx** [comment]
Thanks, i've just tried the latest commit.

The first option (adding an image through the SEO tab) is working perfectly. With the second option (smart image field), i'm getting the following output:

![screenshot 2018-12-17 at 20 22 47](https://user-images.githubusercontent.com/1932778/50110197-f054ee00-0239-11e9-91f6-a9563314f22f.png)

**Comment by adrianbj** [comment]
Have you populated the one on the left or the right?
![image](https://user-images.githubusercontent.com/871211/50110628-9af3ef00-01ef-11e9-9afe-e8432a3e9dab.png)

Obviously the left one is a text field not an image object. If you're using the right one, is the image field set to 1 image or multiple? If one, then you wouldn't want `first()` because it's a single image that will be returned.

Also, I noticed you are back to using `seo_image`, rather than `seo->image` - any reason for the change?

**Comment by qbixx** [comment]
I've added two fields to the right:
![screenshot 2018-12-17 at 20 37 26](https://user-images.githubusercontent.com/1932778/50110883-9f45f980-023b-11e9-9b94-e8c601ac2c8f.png)

> Also, I noticed you are back to using seo_image, rather than seo->image - any reason for the change?

No particular reason :-) I've changed it because you referenced to `seo_image` in your first example.

Just to be safe, i've also tested `seo->image`. With the manual image selection on the SEO tab, everything is working. With the smart image fields, i'm getting the following:

![screenshot 2018-12-17 at 20 42 27](https://user-images.githubusercontent.com/1932778/50111110-49be1c80-023c-11e9-96bd-951d04460d29.png)

**Comment by adrianbj** [comment]
Yeah, but what is the maxfiles setting for header_image and header_image_small. If it's set to one, then you want to get rid of `first()`

**Comment by qbixx** [comment]
Sorry, didn't see that part. Both fields are set to 1 image.

When removing `first()` the result switches. The manually set image doesn't work anymore and the smart image fields are working.

For the manual image field i'm getting:
![screenshot 2018-12-17 at 20 47 33](https://user-images.githubusercontent.com/1932778/50111441-1465fe80-023d-11e9-8a79-fdb8a7fd49f4.png)

This happens with both `seo_image` and `seo->image`

**Comment by adrianbj** [comment]
Try the latest version for me please. I have revamped how the images are handled - hopefully now they will always work as expected.

**Comment by adrianbj** [comment]
Hi @qbixx - any luck with the latest version?

**Comment by qbixx** [comment]
Hi @adrianbj I've just checked the latest version. It's working perfectly! Thanks!

One thing I noticed is that I get an count() error with PHP 7.2
![screenshot 2018-12-20 at 19 30 29](https://user-images.githubusercontent.com/1932778/50303562-bb40d980-048d-11e9-89b6-041d66cf7d8a.png)

**Comment by adrianbj** [comment]
Thanks @qbixx - I have fixed that warning in the latest commit.

Are you OK to close this issue now?

**Comment by qbixx** [comment]
Great! Thanks again for all your help!

Yes, will close this issue.
