### ISSUE TITLE
Error on PHP 7.2

### ISSUE THREAD

**Issue by eelke** [adrianbj/MarkupSEO#6]
Since PHP 7.2 objects that you want to `count()` need to implement `'Countable'`.
As a result, the following throws an error:

https://github.com/adrianbj/MarkupSEO/blob/0d7b30069c2498a58e81fb9c809fa5112e12af51/MarkupSEO.module#L338

A possible fix for now is to first check if it is actually on object:

```
if(isset($pageData['robots']) && gettype($pageData['robots']) === 'object' && count($configData['robots']) !== 0)  {
   foreach($pageData['robots'] as $option) {
      $pageDataRobots[] = $option->title;
   }
}
```

PHP 7.3 will implement `is_countable`.

**Comment by eelke** [comment]
(Edited the issue twice to first introduce an error and then to revert it, haha)

**Comment by adrianbj** [comment]
@eelke - can you please let me know what `$pageData['robots']` actually is when you get this error. I am viewing a page on the frontend with not robots options selected and not seeing this error. I understand the 7.2 changes to count, but I'd like to first ascertain why it's not returning an array.

**Comment by eelke** [comment]
Sure! `gettype($pageData["robots"])` returned `string` when nothing was selected, and `object` when it was.

**Comment by adrianbj** [comment]
Perhaps it's because you have upgraded to my branch of this module so the fieldtype is different? I can't get it to return a string no matter what I do.

I am happy to implement a check though. Although I am curious why you went with `gettype` vs `is_object`?

**Comment by adrianbj** [comment]
I've implemented the fix - also on the code blocks below. Please check the latest version and let me know.

**Comment by adrianbj** [comment]
@eelke - just wanted to see if you have checked my changes? Can this be closed now?

**Comment by eelke** [comment]
> Perhaps it's because you have upgraded to my branch of this module so the fieldtype is different? I can't get it to return a string no matter what I do.
> 
> I am happy to implement a check though. Although I am curious why you went with `gettype` vs `is_object`?

Simply a result of figuring out what was going on here, `is_object` would be preferable.



> @eelke - just wanted to see if you have checked my changes? Can this be closed now?

I did not run into any more errors, so I'll close the issue. Thank you for your fix!
